# action.yml
name: 'Helm template'
description: 'Install Helm, use a template and generate a yaml'
inputs:
  helm-url:
    description: 'URL of the Helm template'
    required: true
  helm-user:
    description: 'Username to use to access the Helm template'
    required: true
  helm-password:
    description: 'Password to use to access the Helm template'
    required: true
  values-file:
    description: 'Path to the optional values file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.helm-url }}
    - ${{ inputs.helm-user }}
    - ${{ inputs.helm-password }}
    - ${{ inputs.values-file }}
